### ISSUE TITLE
Roland is in the repository under two names

### ISSUE THREAD

**Issue by bart1** [movebank/data-repository#6]
https://www.datarepository.movebank.org/browse?rpp=2&order=ASC&sort_by=-1&etal=-1&type=author&starts_with=Kays

Feel free to mark the issues as not going to solve but I thought i would atleast report things i notice

**Comment by sarahcd** [comment]
Yes, there are several individuals listed as authors under different names. Initially I used the same author names as in the related papers, which for many people in the published literature sometimes include middle initials and sometimes not. Once I realized this led to "duplicate" names in the repository I started always using the most complete name for each individual. However this is an inevitable problem in general for publishing author names—even if people include/exclude middle initials consistently, it's not uncommon for a person's name to change during his/her career.

The best solution would probably be to integrate a unique identifier for individuals, maybe ORCIDs (but not everyone has one), into the metadata. Or republish all of the metadata for the existing duplicates caused by middle initial differences. At this point it doesn't seem worth the effort it would take to do this, but it's something to consider if this addition could be included with other improvements.

Note that I have a (separate) submission database in which I do use individual identifiers to connect different names for the same person, so that, for example, I can correctly query for all data packages associated with a person or the number of unique authors represented in the repository.
